"""initial schema

Revision ID: 1773ad942e12
Revises: 
Create Date: 2026-07-20 18:31:55.665634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1773ad942e12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('difficulty_rank', sa.Integer(), nullable=True),
    sa.Column('legal_minutes', sa.Integer(), nullable=False),
    sa.Column('legal_points', sa.Float(), nullable=False),
    sa.Column('goal_minutes', sa.Integer(), nullable=False),
    sa.Column('goal_points', sa.Float(), nullable=False),
    sa.Column('bonus_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('bonus_points', sa.Float(), nullable=False),
    sa.Column('max_session_minutes', sa.Integer(), nullable=True),
    sa.Column('default_location', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_rules_difficulty_rank'), 'activity_rules', ['difficulty_rank'], unique=False)
    op.create_index(op.f('ix_activity_rules_id'), 'activity_rules', ['id'], unique=False)
    op.create_index(op.f('ix_activity_rules_max_session_minutes'), 'activity_rules', ['max_session_minutes'], unique=False)
    op.create_index(op.f('ix_activity_rules_name'), 'activity_rules', ['name'], unique=False)
    op.create_index(op.f('ix_activity_rules_user_id'), 'activity_rules', ['user_id'], unique=False)
    op.create_table('rewards_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_reward_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('required_goal_id', sa.Integer(), nullable=True),
    sa.Column('required_goal_title', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('point_cost', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_archive_id'), 'rewards_archive', ['id'], unique=False)
    op.create_index(op.f('ix_rewards_archive_original_reward_id'), 'rewards_archive', ['original_reward_id'], unique=False)
    op.create_index(op.f('ix_rewards_archive_required_goal_id'), 'rewards_archive', ['required_goal_id'], unique=False)
    op.create_index(op.f('ix_rewards_archive_required_goal_title'), 'rewards_archive', ['required_goal_title'], unique=False)
    op.create_index(op.f('ix_rewards_archive_user_id'), 'rewards_archive', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_rule_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('reward_points', sa.Float(), nullable=False),
    sa.Column('progress_value', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_rule_id'], ['activity_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_activity_rule_id'), 'goals', ['activity_rule_id'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('legal_goal_completed', sa.Boolean(), nullable=False),
    sa.Column('main_goal_completed', sa.Boolean(), nullable=False),
    sa.Column('bonus_intervals', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_rule_id'], ['activity_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_activity_rule_id'), 'sessions', ['activity_rule_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('required_goal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('point_cost', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['required_goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_index(op.f('ix_rewards_required_goal_id'), 'rewards', ['required_goal_id'], unique=False)
    op.create_index(op.f('ix_rewards_user_id'), 'rewards', ['user_id'], unique=False)
    op.create_table('reward_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.Column('reward_name', sa.String(), nullable=False),
    sa.Column('point_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_redemptions_id'), 'reward_redemptions', ['id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_reward_id'), 'reward_redemptions', ['reward_id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_user_id'), 'reward_redemptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_redemptions_user_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_reward_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_id'), table_name='reward_redemptions')
    op.drop_table('reward_redemptions')
    op.drop_index(op.f('ix_rewards_user_id'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_required_goal_id'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_activity_rule_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_activity_rule_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_rewards_archive_user_id'), table_name='rewards_archive')
    op.drop_index(op.f('ix_rewards_archive_required_goal_title'), table_name='rewards_archive')
    op.drop_index(op.f('ix_rewards_archive_required_goal_id'), table_name='rewards_archive')
    op.drop_index(op.f('ix_rewards_archive_original_reward_id'), table_name='rewards_archive')
    op.drop_index(op.f('ix_rewards_archive_id'), table_name='rewards_archive')
    op.drop_table('rewards_archive')
    op.drop_index(op.f('ix_activity_rules_user_id'), table_name='activity_rules')
    op.drop_index(op.f('ix_activity_rules_name'), table_name='activity_rules')
    op.drop_index(op.f('ix_activity_rules_max_session_minutes'), table_name='activity_rules')
    op.drop_index(op.f('ix_activity_rules_id'), table_name='activity_rules')
    op.drop_index(op.f('ix_activity_rules_difficulty_rank'), table_name='activity_rules')
    op.drop_table('activity_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
